git hub deploy initiated

diff --git a/.github/workflows/react.js.yml b/.github/workflows/react.js.yml
--- a/.github/workflows/react.js.yml
+++ b/.github/workflows/react.js.yml
@@ -1,42 +1,61 @@
-name: Build & deploy
-
-on:
+name: Deploy Next.js site to Pages
+'on':
   push:
     branches:
       - main
-  pull_request:
-    branches:
-      - main
-
+  workflow_dispatch: null
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+concurrency:
+  group: pages
+  cancel-in-progress: false
 jobs:
   build:
-    name: Build
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Installing Node.js
-        uses: actions/setup-node@v1
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v3
         with:
-          node-version: 16.x
+          node-version: '16'
+          cache: '${{ steps.detect-package-manager.outputs.manager }}'
+      - name: Setup Pages
+        uses: actions/configure-pages@v3
 
-      - name: Installing NPM packages
-        run: npm ci
+      - name: Install dependencies
+        run: >-
+          ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
 
-      - name: Building project
-        run: npm run build
 
+      - name: Build with React.js
+        run: '${{ steps.detect-package-manager.outputs.runner }}  npm run build'
       - name: Running tests
-        run: npm run test
+        run: npm run test:unit
 
       - name: Uploading production-ready build files
         uses: actions/upload-artifact@v2
         with:
           name: production-files
           path: ./build
-
   deploy:
     name: Deploy
     needs: build
